
name:  Android Build
on: 
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew
#setting up gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

    
